"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ShieldAlert, Activity, ChevronRight, ExternalLink } from "lucide-react";
import { PageHeader, FilterCard, FilterSelect, DataTable, StatusPill, KPICard, TagPill, SeverityBar } from "@/components/platform";
import type { Column, SeverityLevel } from "@/components/platform";
import { createClient } from "@/lib/supabase/client";

interface Incident {
  id: string;
  tenant_id: string;
  title: string | null;
  category: string | null;
  severity: SeverityLevel;
  status: "open" | "triaged" | "closed" | "reopened";
  cluster_key: string | null;
  finding_count: number;
  ai_summary: string | null;
  recommended_action: string | null;
  first_seen: string;
  last_seen: string;
}

export default function IncidentsAdminPage() {
  const supabase = useMemo(() => createClient(), []);
  const [rows, setRows] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterSeverity, setFilterSeverity] = useState("");
  const [filterStatus, setFilterStatus] = useState("");

  useEffect(() => {
    let alive = true;
    const fetchAll = async () => {
      const { data } = await supabase.from("incidents").select("*").order("last_seen", { ascending: false }).limit(200);
      if (!alive) return;
      setRows((data ?? []) as Incident[]);
      setLoading(false);
    };
    void fetchAll();
    const ch = supabase.channel("admin:incidents")
      .on("postgres_changes", { event: "*", schema: "public", table: "incidents" }, () => void fetchAll())
      .subscribe();
    return () => { alive = false; void supabase.removeChannel(ch); };
  }, [supabase]);

  const filtered = useMemo(() => rows.filter((r) => {
    if (filterSeverity && r.severity !== filterSeverity) return false;
    if (filterStatus && r.status !== filterStatus) return false;
    return true;
  }), [rows, filterSeverity, filterStatus]);

  const counts = {
    total: rows.length,
    open: rows.filter((r) => r.status === "open").length,
    critical: rows.filter((r) => r.severity === "Critical").length,
    take: rows.filter((r) => r.recommended_action === "takedown").length,
  };

  const cols: Column<Incident>[] = [
    {
      key: "title",
      header: "Incident",
      render: (r) => (
        <div className="leading-snug max-w-[420px]">
          <p className="text-[12.5px] font-semibold text-slate-200">{r.title ?? r.cluster_key}</p>
          <div className="flex items-center gap-1.5 mt-1">
            {r.category && <TagPill label={r.category} />}
            {r.cluster_key && <span className="text-[10px] text-slate-500 font-mono">{r.cluster_key}</span>}
          </div>
          {r.ai_summary && <p className="text-[10.5px] text-slate-400 mt-1 line-clamp-2">{r.ai_summary}</p>}
        </div>
      ),
    },
    { key: "severity", header: "Severity", render: (r) => <SeverityBar level={r.severity} /> },
    { key: "status", header: "Status", render: (r) => <StatusPill status={r.status.toUpperCase()} /> },
    { key: "count", header: "Findings", align: "right", render: (r) => <span className="text-[12px] text-slate-300 tabular-nums">{r.finding_count}</span> },
    {
      key: "action",
      header: "Recommended",
      render: (r) =>
        r.recommended_action ? (
          <span className="px-1.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider"
            style={{
              background: r.recommended_action === "takedown" ? "rgba(239,68,68,0.10)" : "rgba(168,85,247,0.10)",
              color: r.recommended_action === "takedown" ? "#fca5a5" : "#d8b4fe",
              border: `1px solid ${r.recommended_action === "takedown" ? "rgba(239,68,68,0.30)" : "rgba(168,85,247,0.30)"}`,
            }}>
            {r.recommended_action}
          </span>
        ) : <span className="text-[11px] text-slate-600">—</span>,
    },
    { key: "last", header: "Last seen", render: (r) => <span className="text-[11px] text-slate-500">{new Date(r.last_seen).toLocaleString()}</span> },
    {
      key: "drill",
      header: "",
      render: (r) => (
        <Link href={`/threat-management/incidents?incident_id=${r.id}`}
          className="text-purple-300 hover:text-white text-[11px] font-semibold inline-flex items-center gap-1">
          Findings <ChevronRight className="w-3 h-3" />
        </Link>
      ),
    },
  ];

  return (
    <>
      <PageHeader
        title="Incidents (Grouped Findings)"
        description="AI-grouped clusters of findings — same hosting, same actor, same campaign. Generated by Stage 7 of the upgrade pipeline after AI false-positive filtering."
      />
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">
        <KPICard label="Total Incidents" value={counts.total} accent="purple" icon={ShieldAlert} />
        <KPICard label="Open" value={counts.open} accent="red" icon={Activity} />
        <KPICard label="Critical" value={counts.critical} accent="red" />
        <KPICard label="Pending Takedown" value={counts.take} accent="amber" />
      </div>
      <FilterCard collapsible={false}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <FilterSelect label="Severity" options={["Critical", "Substantial", "Moderate", "Low"]} value={filterSeverity} onChange={setFilterSeverity} />
          <FilterSelect label="Status" options={["open", "triaged", "closed", "reopened"]} value={filterStatus} onChange={setFilterStatus} />
        </div>
      </FilterCard>
      <DataTable<Incident>
        columns={cols}
        rows={filtered}
        rowAction={false}
        emptyText={loading ? "Loading…" : "No incidents yet. Run a full sweep, then an AI process pass."}
      />
    </>
  );
}
